# Generated by Django 5.1.1 on 2024-09-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=30)),
                ('cpf', models.CharField(max_length=11)),
                ('date_born', models.CharField(max_length=11)),
                ('phone', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=200)),
                ('nivel', models.CharField(choices=[('1', 'Iniciante'), ('2', 'Intermediário'), ('3', 'Avançado')], max_length=10)),
            ],
        ),
    ]
