# Generated by Django 5.1.1 on 2024-09-12 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.aluno')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.treino')),
            ],
        ),
    ]
