# Generated by Django 5.1.1 on 2024-09-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='plano',
            field=models.CharField(choices=[('A', 'Mensal'), ('B', 'Semestral'), ('C', 'Anual')], default='C', max_length=10),
        ),
    ]
